#!/usr/bin/env sh
ln -sf /opt/KanYingYin/kanyingyin /usr/bin/kanyingyin
chmod +x /usr/bin/kanyingyin
update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
exit 0