set(FULL_LIBMPV_VERSION "20260610")
set(FULL_LIBMPV_ARCHIVE_NAME "mpv-dev-x86_64-20260610-git-304426c.7z")
set(FULL_LIBMPV_SHA256 "8cbb25ea784f01afbb3f904217cab1317430a8bcfd5680fd827a866367f71cc9")
set(FULL_LIBMPV_CACHE_DIR "${CMAKE_BINARY_DIR}/full_libmpv")
set(FULL_LIBMPV_ARCHIVE "${FULL_LIBMPV_CACHE_DIR}/${FULL_LIBMPV_ARCHIVE_NAME}")
set(FULL_LIBMPV_DIR "${FULL_LIBMPV_CACHE_DIR}/verified")

file(MAKE_DIRECTORY "${FULL_LIBMPV_CACHE_DIR}")

set(FULL_LIBMPV_ARCHIVE_VALID FALSE)
if(EXISTS "${FULL_LIBMPV_ARCHIVE}")
  file(SHA256 "${FULL_LIBMPV_ARCHIVE}" FULL_LIBMPV_CACHED_SHA256)
  if(FULL_LIBMPV_CACHED_SHA256 STREQUAL FULL_LIBMPV_SHA256)
    set(FULL_LIBMPV_ARCHIVE_VALID TRUE)
  else()
    file(REMOVE "${FULL_LIBMPV_ARCHIVE}")
  endif()
endif()

if(NOT FULL_LIBMPV_ARCHIVE_VALID)
  file(DOWNLOAD
    "https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/${FULL_LIBMPV_VERSION}/${FULL_LIBMPV_ARCHIVE_NAME}"
    "${FULL_LIBMPV_ARCHIVE}"
    EXPECTED_HASH "SHA256=8cbb25ea784f01afbb3f904217cab1317430a8bcfd5680fd827a866367f71cc9"
    TLS_VERIFY ON
    SHOW_PROGRESS
  )
endif()

file(REMOVE_RECURSE "${FULL_LIBMPV_DIR}")
file(MAKE_DIRECTORY "${FULL_LIBMPV_DIR}")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E tar xzf "${FULL_LIBMPV_ARCHIVE}"
  WORKING_DIRECTORY "${FULL_LIBMPV_DIR}"
  COMMAND_ERROR_IS_FATAL ANY
)

set(FULL_LIBMPV_DLL "${FULL_LIBMPV_DIR}/libmpv-2.dll")
if(NOT EXISTS "${FULL_LIBMPV_DLL}")
  message(FATAL_ERROR "完整 libmpv 解压后缺少 libmpv-2.dll")
endif()
